version: '3.4'

services:
  adasit.{{cookiecutter.project_name}}.webapi:
    container_name: adasit.{{cookiecutter.ns_name}}.webapi
    image: ${DOCKER_REGISTRY-}adasit{{cookiecutter.ns_name}}webapi
    build:
      context: .
      dockerfile: AdasIt.{{cookiecutter.project_name}}.WebApi/Dockerfile
