version: '3.4'

services:
  adasit.{{cookiecutter.project_name}}.webapi:
    container_name: adasit.{{cookiecutter.ns_name}}.webapi
    depends_on: 
    - "{{cookiecutter.ns_name}}-sql-server-db"
    environment:
      - ASPNETCORE_ENVIRONMENT=Mock
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - {{cookiecutter.ns_name}}-network

  {{cookiecutter.ns_name}}-sql-server-db:
    container_name: {{cookiecutter.ns_name}}-sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - "1433:1433"
    environment:
        SA_PASSWORD: "Adasit#12"
        ACCEPT_EULA: "Y"
    networks:
      - {{cookiecutter.ns_name}}-network

  {{cookiecutter.ns_name}}-flyway:
    container_name: {{cookiecutter.ns_name}}-flyway
    environment:
        - FLYWAY_USER=sa
        - FLYWAY_PASSWORD=Adasit#12
        - FLYWAY_URL=jdbc:sqlserver://{{cookiecutter.ns_name}}-sql-server-db:1433
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
        - ./flyway/sql:/flyway/sql
        - ./Local/database/dev-data:/flyway/sql/dev-data
        - ./Local/database/conf:/flyway/conf
    depends_on:
        - {{cookiecutter.ns_name}}-sql-server-db
    networks:
      - {{cookiecutter.ns_name}}-network
      
    {{cookiecutter.ns_name}}-wiremock:
    container_name: {{cookiecutter.ns_name}}-wiremock
    image: rodolpheche/wiremock
    ports:
    - "8080:8080"
    volumes:
    - ./Local/apis/:/home/wiremock
networks:
    - {{cookiecutter.ns_name}}-network

networks:
  {{cookiecutter.ns_name}}-network:
    driver: bridge